name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.sbt'
      - '.github/workflows/**.yml'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.sbt'
      - '.github/workflows/**.yml'

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
  test_jdk11:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-jdk11-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-jdk11-
      - name: sbt scripted test
        run: ./sbt compile scripted
